### ISSUE TITLE
跟着步骤走，没有播放

### ISSUE THREAD

**Issue by songyunao05** [chenchenwuai/H265Player#2]
请问大佬，跟着操作步骤走了，但是没有播放，有个报错提示是
![1628683665(1)](https://user-images.githubusercontent.com/50287503/129025879-50f85c12-c554-4372-bd3c-4d8cba5d3180.png)
这可能是什么原因呢？

**Comment by chenchenwuai** [comment]
重构了一下逻辑，现在不会出现这个错误了
