### ISSUE TITLE
解码花屏这个是怎么回事呢

### ISSUE THREAD

**Issue by ligengmi** [chenchenwuai/H265Player#3]
大佬可以留个联系方式吗，想咨询你一下

**Comment by chenchenwuai** [comment]
具体怎样花屏的，有图片吗

**Comment by ligengmi** [comment]
大概就是这个样子，我了解了一下，应该是数据流的问题，请问一下大佬，对与数据流的处理有什么好的办法吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenchenwuai/H265Player"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月7日(星期一) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenchenwuai/H265Player] 解码花屏这个是怎么回事呢 (Issue #3)





 
具体怎样花屏的，有图片吗

**Comment by ligengmi** [comment]
大佬，请问一下，您这个播放器支持多路同时播放吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenchenwuai/H265Player"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月7日(星期一) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenchenwuai/H265Player] 解码花屏这个是怎么回事呢 (Issue #3)





 
具体怎样花屏的，有图片吗

**Comment by chenchenwuai** [comment]
我没有处理视频流的经验。如果需要多路同时播放，可以同时实例化多个播放器，但是播放性能会受到视频的分辨率和播放机器性能的影响，例如播放延时

**Comment by ligengmi** [comment]
好的大佬，数据流我已经处理好了，已经不会产生花屏了，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenchenwuai/H265Player"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 上午10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenchenwuai/H265Player] 解码花屏这个是怎么回事呢 (Issue #3)





 
我没有处理视频流的经验。如果需要多路同时播放，可以同时实例化多个播放器，但是播放性能会受到视频的分辨率和播放机器性能的影响，例如播放延时
